name: Node.js CI

on:
  release:
    types: [published]


env:
  REPOSITORY_NAME: gokul4/actions
  VERSION: v1.0.0
  BUILD_NUMBER: ${{ github.run_number }}-${{ github.ref_name }}
  IMAGE_TAG: $REPOSITORY_NAME:$VERSION-b$BUILD_NUMBER

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -  name: Build docker image
         run: docker build -t ${{ env.REPOSITORY_NAME }} .

      -  name: Tag Docker image
         run: docker tag ${{ env.REPOSITORY_NAME }} ${{ env.IMAGE_TAG }}   

      -  name: Push docker image
         run: docker push ${{ env.IMAGE_TAG }}
         
