name: Reverting Docker Images

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: choice
        options:
          - latest
          - latest-1
          - latest-2

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Reverting to selected version
        run: |
          if [[ "$github.event.inputs.environment" == "latest" ]]; then
            curl -s https://registry.hub.docker.com/v2/repositories/gokul4/qa/tags?page_size=100 | jq -r '.results[0].name' >> "$tag"
            echo "$tag"
            docker pull gokul4/prod:$tag          
          fi  
        
