name: Reverting Docker Images

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: choice
        options:
          - latest
          - latest-1
          - latest-2

env:
  REPO: gokul4/dev

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Reverting to selected version
        run: |
          # Fetch the tag version
          TAGS=($(curl -s "https://registry.hub.docker.com/v2/repositories/gokul4/qa/tags?page_size=100" | jq -r '.results[].name'))

          # Condition
          if [[ "${{ github.event.inputs.environment }}" == "latest" ]]; then
            SELECTED_TAG=${TAGS[0]}
          elif [[ "${{ github.event.inputs.environment }}" == "latest-1" ]]; then
            SELECTED_TAG=${TAGS[1]}
          elif [[ "${{ github.event.inputs.environment }}" == "latest-2" ]]; then
            SELECTED_TAG=${TAGS[2]}
          else
            echo "Failed"
          fi

          #Pull
          docker pull ${env.REPO}:$SELECTED_TAG
