name: Reverting Docker Images

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select the environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

    
      environment:
        description: 'Select the dcoker image version to deploy'
        required: true
        type: choice
        options:
          - latest
          - latest-1
          - latest-2
  
env:
  REPO: ${{ format('gokul4/{0}', github.event.inputs.platform) }}

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Reverting to selected version
        run: |
          # Fetch the tag version
          TAGS=($(curl -s "https://registry.hub.docker.com/v2/repositories/${{env.REPO}}/tags?page_size=100" | jq -r '.results[].name'))

          # Condition
          if [[ "${{ github.event.inputs.environment }}" == "latest" ]]; then
            SELECTED_TAG=${TAGS[0]}
          elif [[ "${{ github.event.inputs.environment }}" == "latest-1" ]]; then
            SELECTED_TAG=${TAGS[1]}
          elif [[ "${{ github.event.inputs.environment }}" == "latest-2" ]]; then
            SELECTED_TAG=${TAGS[2]}
          else
            echo "Failed"
          fi

      - name: Deployment to the server 
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{ secrets.IP }}
            USER_NAME: ${{ secrets.USER_NAME }} 
            SELECTEDTAG : ${{ env.SELECTED_TAG }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              docker pull ${{env.REPO}}:$SELECTEDTAG

              '
         
          
